version: '3.8'

services:
  server:
    build: ./server
    ports:
      - 1234:1234
    volumes:
      - ./server:/app
      - /app/node_modules
    links:
      - db
    depends_on:
      - db

  db:
    image: mongo:7.0.5-rc0-jammy
    restart: always
    ports:
      - 27017:27017
    volumes:
      - codeforces:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password   

  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  codeforces:                  

