version: '3.8'

services:
  server:
    build: ./Server
    ports:
      - 1234:1234
    # volumes:
    #   - ./server:/app
    #   - /app/node_modules
    develop:
      watch: 
        - action: sync
          path: ./Server
          target: /app
          ignore:
            - ./Server/node_modules/
        - action: rebuild
          path: ./Server/package.json
    links:
      - db
      - redis
    depends_on:
      - db

  db:
    image: mongo:7.0.5-rc0-jammy
    restart: always
    ports:
      - 27017:27017
    volumes:
      - codeforces:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password   

  client:
    build: ./Client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules

  redis:
    image: redis:7.2.3-alpine    

volumes:
  codeforces:                  

