const path = {
  PUBLIC: "/",
  HOME: "home",
  LOGIN: "/login",
  STAR: "*",
  API_SEARCH_ALL: "/search",
  USER: "/profile/:id",
  IDE: "/ide",
  SETTING: "/setting/:username",
  SIGNUP: "/signup",
  RATING: "/rating",
  CALENDAR: "/calendar",
  SEARCH: "/search",
  WRITEBLOG: "/writeblog",
  BLOG: "/blog/:blog",
  MESSAGE: "/message/:user",
  PROBLEM: "/problem/:id",
  PROBLEMS: "/problems",
  CREATEPROBLEM: "/createproblem",
  EDITPROBLEM: "/editproblem/:id",
  VERIFY_EMAIL: "/verify",
  EDITBLOG: "/editblog/:id",
  SUBMIT: "/profile/submissions/:author/:page",
  CHAT: "/chat",
  CONTEST: "/contests",
  CONTESTDETAIL: "/contest/:id",
  VIRTUALCONTESTDETAIL: "/virtual-contest/:id",
  CONTESTSTANDING: "/contest/:id/standing",
  SUBMITDETAIL: "/submission/:id",
  FORGOTPASSWORD: "/forgot-password",
  RESETPASSWORD: "/api/auth/reset-password/:token/:email",
  POLYGON: "/polygon",
};
export default path;
