server:
    port: 8080

spring:
    main:
        web-application-type: reactive
    application:
        name: api-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            routes:
                -   id: auth
                    uri: lb://auth
                    predicates:
                        - Path=/api/v1/auth/**

eureka:
    client:
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka/

jwt:
    public-key-path: /home/mimingucci/Work/Java/Codeforces/public-key.pem