server:
    port: 8080

spring:
    main:
        web-application-type: reactive
    application:
        name: api-gateway
    cloud:
        gateway:
            globalcors:
                corsConfigurations:
                    '[/api/v1/**]':
                        allowedOrigins: "http://localhost:3000"
                        allowedHeaders: "*"
                        allowedMethods:
                            - GET
                            - POST
                            - PUT
                            - DELETE
                            - PATCH
                            - OPTIONS
                            - HEAD
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            routes:
                -   id: auth
                    uri: lb://auth
                    predicates:
                        - Path=/api/v1/auth/**
                -   id: submission
                    uri: lb://submission
                    predicates:
                        - Path=/api/v1/submission/**
                -   id: blog
                    uri: lb://blog
                    predicates:
                        - Path=/api/v1/blog/**
                -   id: comment
                    uri: lb://comment
                    predicates:
                        - Path=/api/v1/comment/**
                -   id: contest
                    uri: lb://contest
                    predicates:
                        - Path=/api/v1/contest/**
                -   id: problem
                    uri: lb://problem
                    predicates:
                        - Path=/api/v1/problem/**
                -   id: testcase
                    uri: lb://testcase
                    predicates:
                        - Path=/api/v1/testcase/**
                -   id: user
                    uri: lb://user
                    predicates:
                        - Path=/api/v1/user/**
                -   id: ranking
                    uri: lb://ranking
                    predicates:
                        - Path=/api/v1/ranking/**
                -   id: chat
                    uri: lb:ws://user
                    predicates:
                        - Path=/api/v1/chat/**
                    metadata:
                        protocol: ws


eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/

jwt:
    public-key-path: /home/mimingucci/Work/Java/Codeforces/public-key.pem