server:
    port: 8080

spring:
    main:
        web-application-type: reactive
    application:
        name: api-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            routes:
                -   id: auth
                    uri: lb://auth
                    predicates:
                        - Path=/api/v1/auth/**
                -   id: submission
                    uri: lb://submission
                    predicates:
                        - Path=/api/v1/submission/**
                -   id: blog
                    uri: lb://blog
                    predicates:
                        - Path=/api/v1/blog/**
                -   id: comment
                    uri: lb://comment
                    predicates:
                        - Path=/api/v1/comment/**
                -   id: contest
                    uri: lb://contest
                    predicates:
                        - Path=/api/v1/contest/**
                -   id: problem
                    uri: lb://problem
                    predicates:
                        - Path=/api/v1/problem/**
                -   id: user
                    uri: lb://user
                    predicates:
                        - Path=/api/v1/user/**


eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/

jwt:
    public-key-path: /home/mimingucci/Work/Java/Codeforces/public-key.pem