spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service
          predicates:
            - Path=/users/**
          filters:
            - AuthFilter

        - id: auth-service
          uri: http://auth-service
          predicates:
            - Path=/auth/**

        - id: product-service
          uri: http://product-service
          predicates:
            - Path=/products/**
          filters:
            - AuthFilter