server:
  port: 8087

spring:
  application:
    name: submission

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: submission

jwt:
  private-key: /keys/private-key.pem
  public-key: /keys/public-key.pem

# MOSS configuration
moss:
  script:
    path: /app/moss
  temp:
    dir: /tmp/moss
