const path = {
  PUBLIC: "/",
  HOME: "home",
  LOGIN: "/login",
  STAR: "*",
  API_SEARCH_ALL: "/search",
  USER: "/profile/:username",
  IDE: "/ide",
  SETTING: "/profile/:user/setting",
  SIGNUP: "/signup",
  RATING: "/rating",
  CALENDAR: "/calendar",
  SEARCH: "/search",
  WRITEBLOG: "/writeblog",
  BLOG: "/blog/:blog",
  MESSAGE: "/message/:user",
  PROBLEM: "/problem/:id",
  PROBLEMS: "/problems",
  CREATEPROBLEM: "/createproblem",
  EDITPROBLEM: "/editproblem/:id",
  EDITBLOG: "/editblog/:id",
};
export default path;
