version: "3.8"
services:
  judger:
    build:
      context: .
    privileged: true  # Add this line
    cap_add:
      - SYS_PTRACE
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ./tests/test_case:/test_case:ro
      - ./log:/log
      - ./run:/judger
    environment:
      BACKEND_URL: "http://backend:80/api/judge_server_heartbeat"
      SERVICE_URL: "http://judge-server:12358"
      TOKEN: "toivaban12345"
      DEBUG_MODE: "1"
      INSTANCE_HOST: ${INSTANCE_HOST:-host.docker.internal}
    ports:
      - "8090:8090"