server:
  port: 8085

spring:
  application:
    name: contest

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: contest

jwt:
  private-key: /keys/private-key.pem
  public-key: /keys/public-key.pem
