server:
  port: 8089

spring:
  application:
    name: ranking
  kafka:
    bootstrap-servers: kafka:29092
  datasource:
    url: jdbc:mysql://mysql:3306/codeforces?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Andrew1122:))
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

# Completely disable Eureka client during startup to ensure properties are properly loaded
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: false
    hostname: ranking
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 10
    ip-address: ranking

redis:
  host: redis
  port: 6379

jwt:
  public-key: /keys/public-key.pem
  private-key: /keys/private-key.pem
